version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: "maria_db"
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: go-movies
    volumes:
      - ./data/maria_data/:/var/lib/mysql

volumes:
  data: