version: '3'

services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: go-movies
    volumes:
      - ./data/maria_data/:/var/lib/mysql
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    depends_on:
      - user-service
      - movie-service
    
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    hostname: user_app
    depends_on:
      - mariadb
    restart: always
    
  movie-service:
    build: 
      context: ./movie-service
      dockerfile: Dockerfile
    hostname: movie_app
    depends_on:
      - mariadb
    restart: always
    

