version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: "maria_db"
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: go-movies
    volumes:
      - ./data/maria_data/:/var/lib/mysql
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "4000:80"
  movie-service:
    build: 
      context: ./movie-service
      dockerfile: Dockerfile
    ports:
      - "5000:80"

volumes:
  data: